### ISSUE TITLE
meshclust2 terminates with cryptic error message if fed any sequence of just Ns 

### ISSUE THREAD

**Issue by mnapolitano89** [TulsaBioinformaticsToolsmith/MeShClust2#1]
If you have a sequence in an input fasta file that is just Ns, you get this error thrown: 

➜ new_fasta_files ~  ../../MeShClust2/bin/meshclust2 ./sample_set.fasta
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
[1]    934 abort (core dumped)  ../../MeShClust2/bin/meshclust2 ./sample_set.fasta

Took me a bit of time to figure out what was causing the error, could see it being confusing for others.

**Comment by hani-girgis** [comment]
This issues has been fixed in MeShClust v3.0, which can be obtained from https://github.com/BioinformaticsToolsmith/Identity.git

Let us know if you have any questions.
