### ISSUE TITLE
meshclust2 fails to compile on macOS mojave with g++-8

### ISSUE THREAD

**Issue by mnapolitano89** [TulsaBioinformaticsToolsmith/MeShClust2#2]
The compile error is 
```
src/Loader.cpp: In instantiation of 'std::vector<Point<T>*> Loader<T>::load_next(int) [with T = double]':
src/Loader.cpp:106:16:   required from here
src/Loader.cpp:81:26: error: cannot bind non-const lvalue reference of type 'uintmax_t&' {aka 'long unsigned int&'} to an rvalue of type 'uintmax_t' {aka 'long unsigned int'}
```

**Comment by mnapolitano89** [comment]
Not sure what's causing it / how best to provide info for troubleshooting, but I was able to get it compiled successfully on an aws instance.

**Comment by hani-girgis** [comment]
The newest version of MeShClust (v3.0) can be obtained from https://github.com/BioinformaticsToolsmith/Identity.git

Let us know if you have any questions.
