### ISSUE TITLE
MeShClust2 fails to compile on Red Hat 6.7 with g++ 5.3.0

### ISSUE THREAD

**Issue by cruizperez** [TulsaBioinformaticsToolsmith/MeShClust2#3]
The compile error is:
/tmp/ccO4dw93.s: Assembler messages:
/tmp/ccO4dw93.s:146: Error: no such instruction: `vpbroadcastd %xmm0,%ymm0'
/tmp/ccO4dw93.s:149: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:153: Error: no such instruction: `vperm2i128 $1,%ymm0,%ymm0,%ymm1'
/tmp/ccO4dw93.s:154: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:156: Error: suffix or operands invalid for `vpsrldq'
/tmp/ccO4dw93.s:157: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:158: Error: suffix or operands invalid for `vpsrldq'
/tmp/ccO4dw93.s:159: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:667: Error: no such instruction: `vpbroadcastd %xmm0,%ymm0'
/tmp/ccO4dw93.s:670: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:674: Error: no such instruction: `vperm2i128 $1,%ymm0,%ymm0,%ymm1'
/tmp/ccO4dw93.s:675: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:677: Error: suffix or operands invalid for `vpsrldq'
/tmp/ccO4dw93.s:678: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:679: Error: suffix or operands invalid for `vpsrldq'
/tmp/ccO4dw93.s:680: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:6068: Error: no such instruction: `vpbroadcastd %xmm0,%ymm0'
/tmp/ccO4dw93.s:6514: Error: no such instruction: `vpbroadcastd %xmm0,%ymm0'
/tmp/ccO4dw93.s:16117: Error: no such instruction: `vpbroadcastd %xmm0,%ymm0'
/tmp/ccO4dw93.s:16120: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:16124: Error: no such instruction: `vperm2i128 $1,%ymm0,%ymm0,%ymm1'
/tmp/ccO4dw93.s:16125: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:16127: Error: suffix or operands invalid for `vpsrldq'
/tmp/ccO4dw93.s:16128: Error: suffix or operands invalid for `vpmaxsd'
/tmp/ccO4dw93.s:16129: Error: suffix or operands invalid for `vpsrldq'
/tmp/ccO4dw93.s:16130: Error: suffix or operands invalid for `vpmaxsd'
make[1]: *** [../bin/nonltr/TableBuilder.o] Error 1
make[1]: Leaving directory `MeShClust2/src'
make: *** [bin/Red.o] Error 2

Note: I have tried compiling with other g++ versions, but all of them fail.

**Comment by benjamin-james** [comment]
Can you try removing "-march=native" from the CXXFLAGS variable
src/cluster/Makefile? Otherwise, please try to compile on the same platform
you plan to run the binary on.

**Comment by cruizperez** [comment]
It worked when I removed "-march=native" from the CXXFLAGS variable in both src/cluster/Makefile and src/Makefile. Thanks!

**Comment by nsabinjr** [comment]
I think I'm having a similar problem
Only my compilation is failing on a WSL Ubuntu distro
And I'm not quite sure what you guys have explained here^ for RedHat

My last couple output statements while compiling were:


[ 73%] Building CXX object CMakeFiles/Predict.dir/src/predict/GreedySelector.cpp.o
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp: In instantiation of ‘std::pair<Feature<T>*, matrix::GLM> GreedySelector<T>::train_regression(Feature<T>*, const std::vector<pra<T> >&, const std::vector<pra<T> >&) [with T = unsigned char]’:
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:149:16:   required from here
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:76:1: warning: no return statement in function returning non-void [-Wreturn-type]
   76 | }
      | ^
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp: In instantiation of ‘std::pair<Feature<T>*, matrix::GLM> GreedySelector<T>::train_regression(Feature<T>*, const std::vector<pra<T> >&, const std::vector<pra<T> >&) [with T = short unsigned int]’:
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:150:16:   required from here
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:76:1: warning: no return statement in function returning non-void [-Wreturn-type]
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp: In instantiation of ‘std::pair<Feature<T>*, matrix::GLM> GreedySelector<T>::train_regression(Feature<T>*, const std::vector<pra<T> >&, const std::vector<pra<T> >&) [with T = unsigned int]’:
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:151:16:   required from here
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:76:1: warning: no return statement in function returning non-void [-Wreturn-type]
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp: In instantiation of ‘std::pair<Feature<T>*, matrix::GLM> GreedySelector<T>::train_regression(Feature<T>*, const std::vector<pra<T> >&, const std::vector<pra<T> >&) [with T = long unsigned int]’:
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:152:16:   required from here
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:76:1: warning: no return statement in function returning non-void [-Wreturn-type]
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp: In instantiation of ‘std::pair<Feature<T>*, matrix::GLM> GreedySelector<T>::train_regression(Feature<T>*, const std::vector<pra<T> >&, const std::vector<pra<T> >&) [with T = int]’:
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:153:16:   required from here
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:76:1: warning: no return statement in function returning non-void [-Wreturn-type]
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp: In instantiation of ‘std::pair<Feature<T>*, matrix::GLM> GreedySelector<T>::train_regression(Feature<T>*, const std::vector<pra<T> >&, const std::vector<pra<T> >&) [with T = double]’:
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:154:16:   required from here
/mnt/c/Users/Norman/Downloads/Meshclust2/src/predict/GreedySelector.cpp:76:1: warning: no return statement in function returning non-void [-Wreturn-type]
[ 75%] Building CXX object CMakeFiles/Predict.dir/src/predict/BestFirstSelector.cpp.o
[ 77%] Linking CXX static library libPredict.a
[ 77%] Built target Predict
Scanning dependencies of target Fastcar
[ 78%] Building CXX object CMakeFiles/Fastcar.dir/src/fastcar/FC_Runner.cpp.o
[ 80%] Linking CXX static library libFastcar.a
[ 83%] Built target Fastcar
make[2]: *** No rule to make target 'CMakeFiles/fastcar.dir/depend'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:98: CMakeFiles/fastcar.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by nsabinjr** [comment]
Or maybe I'm past the compilation because it starts off with:

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/c/Users/Norman/Downloads/Meshclust2/bin

**Comment by hani-girgis** [comment]
The newest version of MeShClust (v3.0) can be obtained from https://github.com/BioinformaticsToolsmith/Identity.git

Let us know if you have any questions.
