### ISSUE TITLE
Errors -id >0.99 

### ISSUE THREAD

**Issue by maedat** [TulsaBioinformaticsToolsmith/MeShClust2#4]
I had below error messages with a parameter -id >0.99 (e.g. 0.995) on MeShClust2 (Version 2.3.0 compiled with OpenMP 201307, centOS ). 

Error of feature: manhattan. The maximum distance cannot be zero.
terminate called after throwing an instance of 'std::exception'
  what():  std::exception

MeShClust(Version 1.2.0) worked well with this parameter but gave a warning 
" Warning: Alignment may be too large for sampling"

I want to detect weak differences among the long PacBio CCS reads (>2000 bp). 
Do you have any idea?

**Comment by hani-girgis** [comment]
I am happy to help. In order to reproduce this error on my machine, would you share the input sequences that caused this error? My email address is hzgirgis at buffalo dot edu

**Comment by maedat** [comment]
Thank you for your kind reply. 
I send my sequence file via e-mail.
