### ISSUE TITLE
compiling issue: incomplete type

### ISSUE THREAD

**Issue by Ruonan0101** [TulsaBioinformaticsToolsmith/MeShClust2#5]
Hi,
when make, I have the following error. Could you help to check? thanks~

error: field ‘uint64_t’ has incomplete type
  Chromosome(uint64_t);

**Comment by hani-girgis** [comment]
The newest version of MeShClust (v3.0) can be obtained from https://github.com/BioinformaticsToolsmith/Identity.git

Let us know if you have any questions.
