### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Snowseed** [TulsaBioinformaticsToolsmith/MeShClust2#6]
hi,
I had below error messages with a default parameter  meshclust2 *.fasta
Error of feature:Illegal instruction (core dumped)
Could you help to check? thanks~

**Comment by nvpatin** [comment]
I've gotten the same error with both meshclust and meshclust2 after installing in a conda environment. I confirmed that gcc version was 4.9.4. Any ideas on what might be causing this issue?

**Comment by kavonrtep** [comment]
I am getting same error as nvpatin

**Comment by hani-girgis** [comment]
This issue has been fixed in MeShClust v3.0

The newest version of MeShClust (v3.0) can be obtained from https://github.com/BioinformaticsToolsmith/Identity.git

Let's us know if you have any questions.
