### ISSUE TITLE
Illegal instruction after sequence are read // conda installation

### ISSUE THREAD

**Issue by klamkiew** [TulsaBioinformaticsToolsmith/MeShClust2#7]
Hi there,

I just installed meshclust2 via conda (version 2.3.0) in a completely new environment and wanted to cluster some viral data; I have 242 sequences with a length of 10 - 11 kb, some of which containing some "N" in their sequence. The longest N-stretch in the dataset has a length of 173 - the rest are canonical nucleotides (A, C, G, T)

When meshclust2 is invoked the simplest way (`meshclust2 data.fasta`) I get the following output -- it seems like meshclust runs into an error when the k-mer counting starts?!

I reproduced with the same behavior with similar datasets - similar sequence length but a different number of sequences.

```
meshclust2 data.fasta
avg length: 21594
Recommended K: 7
Reading in sequences [=================================================] 100 %
Largest count: 44
Using 8 bit histograms
Illegal instruction                                                    ] 0 %

```

**Comment by hani-girgis** [comment]
Hi, Kevin.

Thanks for trying out MeShClust2.

I would recommend:
1. Using the --datatype parameter with larger datatype, perhaps 32 bits; these are longer sequences. 
2. If the identity among these sequences is low (less than 60%), please try MeShClust1 (BioinformaticsToolsmith/MeShClust).
3. If the above two options did not work for you, please email me the input data at hzgirgis at buffalo dot edu

Best regards.

Hani Zakaria

**Comment by klamkiew** [comment]
Tried both options - just as a short note:

```
$> meshclust --help

Usage: [...]

If using long sequences or low (<60%) identity, use MeShClust2 (https://github.com/TulsaBioinformaticsToolsmith/MeShClust2).
```

This states the opposite of your option 2, or am I missing something? That help message led me to use meshclust2 ;)

Anyway, I will happily send you the input data.

Quick edit:
Just to clarify; I tried both suggesstions without success.

**Comment by hani-girgis** [comment]
Hello, Kevin. 

I am unable to obtain the error you got. I have tried the following commands (in addition to the one you mentioned) and all of them finished without errors:

 meshclust2 file.fna --id 0.7 --output meshclust2_0.7.txt --datatype 16 --feat slow
 meshclust2 file.fna --id 0.8 --output meshclust2_0.8.txt --datatype 16 --feat slow
 meshclust2 file.fna --id 0.9 --output meshclust2_0.9.txt --datatype 16 --feat slow
 meshclust2 file.fna --id 0.95 --output meshclust2_0.95.txt --datatype 16 --feat slow
meshclust2 file.fna --id 0.97 --output meshclust2_0.97.txt --datatype 16 --feat slow 

First, I noticed that these sequences are highly similar to each other that is why I used higher identity scores (0.95 and 0.97) and these two runs produced good clusters based on the names of the sequences (please confirm). I will email these files to you via email. 

MeShClust can handle sequences including N's. So this should not be the issue. 

Are you using g++-7 or higher? 

I would recommend clean installation with g++-7 or g++-8 or higher. 

Best, 

Hani Zakaria

**Comment by klamkiew** [comment]
Hello Hani,

the cluster look good at first glance, thanks a lot. In the meantime, I updated g++ to version 7.5.0, however, I am still receiving the Illegal Instruction error. I'll try to contact our system admins to update g++ globally (that one is version 6.3.0) - I only have permissions to install some local stuff, maybe some system libraries are causing my issues here.

**Comment by hani-girgis** [comment]
Hello, Kevin.

Have you updated the compiler in the CMakeLists.txt or used the CXX=g++-7 (or where the new compiler is)?

Best regards,

Hani Zakaria

**Comment by klamkiew** [comment]
Hello Hani,
so apparently there has been some old library that cause my issues. I set up a complete new environment on a laptop with the newest versions of gcc / g++, compiled meshclust and meshclust2 again and it worked like a charm. 
Thank you a lot for your patience and support :+1: 

Cheers,
Kevin
