### ISSUE TITLE
Irritating results with a certain identity input

### ISSUE THREAD

**Issue by YSchaefer** [TulsaBioinformaticsToolsmith/MeShClust2#9]
Dear developers,

I used meshclust2 on 1851 sequences which are around 6 kb long and since the differences between these sequences vary, I ran meshclust2 with different identities 10 times each.
As expected, there are more clusters the higher the shared identity between sequences has to be. However, there is a drop of the number of clusters at around 0.93 input identity (see plot). In these meshclust runs, there is one huge cluster which contains a majority of all sequences. It does not make sense that all of these sequences share this high identity all of a sudden when they did not in the runs before. I wonder what is going on in these runs.

Thanks in advance for your help!

![image](https://user-images.githubusercontent.com/78353867/148942519-cd04e46d-7a31-4109-a73f-76d265638f8c.png)

**Comment by hani-girgis** [comment]
Thanks for reaching out to us. 

In order to understand what is going on with MeShClust 2, is it possible to provide the 1851 sequences? If you agree, please send them to me via email (hzgirgis at buffalo dot edu). I will keep your data confidential! 

Best regards.

**Comment by hani-girgis** [comment]
Please post your questions on the new repository: https://github.com/BioinformaticsToolsmith/Identity.git

Thanks.
